DECLARE @DBNAME nvarchar(MAX) 
DECLARE @GROUP_NAME nvarchar(MAX) 
DECLARE @GROUP_NAME_LOG nvarchar(MAX) 
DECLARE @FILEPATH nvarchar(MAX) 
DECLARE @FILEPATH_LOG nvarchar(MAX) 

SET @DBNAME = N'TestDB'
SET @GROUP_NAME = N'TestDB'
SET @FILEPATH = N'E:\DatabaseFiles\TestDB.mdf'
SET @FILEPATH_LOG = N'E:\DatabaseFiles\TestDB_log.ldf'


DECLARE @SQL nvarchar(max);
SET @SQL = N'CREATE DATABASE [' + @DBNAME + '] ON PRIMARY (NAME = ' + @GROUP_NAME + '_Data, FILENAME = ''' + @FILEPATH + ''' , SIZE = 30720KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%) LOG ON ( NAME = ' + @GROUP_NAME + '_Log, FILENAME = ''' + @FILEPATH_LOG + ''', SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)'
EXEC (@SQL)
GO